name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    name: check_eslint_error
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: eslint review
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-check
        eslint_flags: './**/*.{vue,ts,js}'
